using System.Collections.Generic;
using UnityEngine;

namespace EscapeFromWork.Level
{
    /// <summary>
    /// Complete layout of a single floor. Generated by <see cref="FloorBuilder"/>
    /// and consumed by SceneWirer.
    /// </summary>
    [System.Serializable]
    public class FloorLayoutData
    {
        public int floorNumber;
        public int seed;

        /// <summary>Which layout archetype this floor uses.</summary>
        public FloorBuilder.FloorArchetype archetype;

        /// <summary>Bounding rect of the core筒 + ring corridor (blocked zone).</summary>
        public Rect ringCorridorRect;

        /// <summary>Player spawn point (center of entry stairwell).</summary>
        public Vector2 entryPos;

        /// <summary>Extraction point (center of farthest stairwell).</summary>
        public Vector2 extractPos;

        /// <summary>Core筒 interior tea room center (safe room).</summary>
        public Vector2 teaRoomPos;

        /// <summary>True every 5 floors — spawns an extra luxury tea bar in open area.</summary>
        public bool hasLuxuryTeaBar;

        // ── Rooms ──────────────────────────────────────────────────────

        public List<RoomDef> rooms = new List<RoomDef>();

        // ── Open-plan elements ─────────────────────────────────────────

        public List<DeskClusterDef> deskClusters = new List<DeskClusterDef>();
        public List<PartitionDef> partitions = new List<PartitionDef>();
        public List<Vector2> columns = new List<Vector2>();

        // ── Difficulty ─────────────────────────────────────────────────

        public int enemyCount = 10;
        public float partitionDensity = 0.3f;

        // ── High-value zone ────────────────────────────────────────────

        /// <summary>Center of this floor's high-value core zone.</summary>
        public Vector2 highValueZonePos;

        /// <summary>Type label (Executive Suite, Department Vault, Server Core, etc.).</summary>
        public string highValueZoneType = "Standard";
    }

    /// <summary>
    /// A walled room on the floor layout.
    /// </summary>
    [System.Serializable]
    public class RoomDef
    {
        public RoomType roomType;

        /// <summary>Bottom-left corner in world space (XZ plane).</summary>
        public Vector2 worldPos;

        /// <summary>Width (X) × Depth (Z) in world units.</summary>
        public Vector2 size;

        /// <summary>World position of the door centre.</summary>
        public Vector2 doorPos;

        // ── Spatial attributes (Phase 2) ────────────────────────────────

        /// <summary>Which spatial zone this room belongs to.</summary>
        public ZoneLevel zoneLevel;

        /// <summary>True when the room touches an exterior wall (has windows).</summary>
        public bool hasWindows;

        /// <summary>Department cluster tag, e.g. "HR", "Finance", "IT", "Executive".</summary>
        public string departmentTag;

        /// <summary>Lock level: 0 = none, 1 = standard lock, 2 = keypad, 3 = electronic.</summary>
        public int lockLevel;

        /// <summary>Password / key code if locked. Null when lockLevel = 0.</summary>
        public string lockPassword;

        /// <summary>Label of the room where the password hint can be found.</summary>
        public string passwordHintRoomLabel;

        /// <summary>Labels of rooms sharing a wall with this room.</summary>
        public List<string> connectedRoomLabels = new List<string>();

        /// <summary>Which side the door is on (for AI / sound / sightline queries).</summary>
        public DoorDirection doorSide;
    }

    /// <summary>
    /// An open-plan desk cluster — no walls, just desks + low partitions.
    /// </summary>
    [System.Serializable]
    public class DeskClusterDef
    {
        public Vector2 center;
        public Vector2 size;
        public int deskCount;

        /// <summary>Cardinal facing in degrees (0, 90, 180, 270).</summary>
        public float facing;
    }

    /// <summary>
    /// A partition wall segment between desk clusters.
    /// </summary>
    [System.Serializable]
    public class PartitionDef
    {
        public Vector2 start;
        public Vector2 end;

        /// <summary>1.2m = low (crouch cover), 1.8m = high (full visual block).</summary>
        public float height;
    }

    /// <summary>
    /// A straight corridor segment.
    /// </summary>
    [System.Serializable]
    public class CorridorSeg
    {
        public Vector2 start;
        public Vector2 end;
        public float width;
        public bool isMainCorridor;
    }
}
